const DEFAULTS={focus:25,short:5,long:15,dailyGoal:120,darkness:58,blur:2};
const state={mode:'focus',running:false,remaining:DEFAULTS.focus*60,intervalId:null,endAt:null,settings:loadJSON('bernaSettings',DEFAULTS),stats:loadJSON('bernaStats',{date:todayKey(),minutes:0,pomodoros:0,streak:0,lastStudyDate:null})};
const $=(s)=>document.querySelector(s);
const timer=$('#timer'),startButton=$('#startButton'),resetButton=$('#resetButton'),modeLabel=$('#modeLabel'),sessionHint=$('#sessionHint'),todayMinutes=$('#todayMinutes'),pomodoroCount=$('#pomodoroCount'),streakCount=$('#streakCount'),streakMessage=$('#streakMessage'),goalLabel=$('#goalLabel'),goalPercent=$('#goalPercent'),progressBar=$('#progressBar'),subjectSelect=$('#subjectSelect'),settingsDialog=$('#settingsDialog'),mikiScene=$('#mikiScene'),mikiMessage=$('#mikiMessage'),photoBackground=$('#photoBackground'),toast=$('#toast');
function loadJSON(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value?{...fallback,...value}:{...fallback}}catch{return{...fallback}}}
function todayKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return`${y}-${m}-${d}`}
function previousDayKey(){const d=new Date();d.setDate(d.getDate()-1);return todayKey(d)}
function ensureCurrentDay(){const today=todayKey();if(state.stats.date!==today){state.stats.date=today;state.stats.minutes=0;state.stats.pomodoros=0;saveStats()}}
function durationFor(mode){return Math.max(1,Number(state.settings[mode])||DEFAULTS[mode])*60}
function setMode(mode){stopTimer();state.mode=mode;state.remaining=durationFor(mode);document.querySelectorAll('.mode-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.mode===mode));const labels={focus:['ODAK ZAMANI','Telefonu bırak. Sadece bu oturuma odaklan.'],short:['KISA MOLA','Nefes al, su iç ve gözlerini dinlendir.'],long:['UZUN MOLA','Biraz uzaklaş. Zihnini gerçekten dinlendir.']};modeLabel.textContent=labels[mode][0];sessionHint.textContent=labels[mode][1];renderTimer();renderMiki()}
function renderTimer(){const minutes=Math.floor(state.remaining/60),seconds=state.remaining%60;timer.textContent=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`;document.title=`${timer.textContent} · Berna`}
function toggleTimer(){state.running?stopTimer():startTimer()}
function startTimer(){if(state.running)return;state.running=true;state.endAt=Date.now()+state.remaining*1000;startButton.textContent='Duraklat';state.intervalId=window.setInterval(tick,250);renderMiki()}
function stopTimer(){state.running=false;state.endAt=null;startButton.textContent='Başlat';if(state.intervalId)window.clearInterval(state.intervalId);state.intervalId=null;renderMiki()}
function tick(){const next=Math.max(0,Math.ceil((state.endAt-Date.now())/1000));if(next!==state.remaining){state.remaining=next;renderTimer();renderMiki()}if(next===0)completeSession()}
function focusProgress(){const total=durationFor('focus');return Math.min(1,Math.max(0,(total-state.remaining)/total))}
function renderMiki(){mikiScene.className='miki-scene';if(state.mode!=='focus'){mikiScene.classList.add('sleeping','stage-0');mikiMessage.textContent=state.mode==='short'?'Miki de kısa bir mola veriyor.':'Miki minderde dinleniyor.';return}if(!state.running&&state.remaining===durationFor('focus')){mikiScene.classList.add('sleeping','stage-0');mikiMessage.textContent='Miki seninle çalışmaya hazır.';return}const p=focusProgress();let stage=p<.2?0:p<.55?1:p<.85?2:3;mikiScene.classList.add(`stage-${stage}`);if(state.running)mikiScene.classList.add('running');const messages=['Miki uyandı. Hadi başlayalım.','Miki sessizce yanında.','Miki kitabını açtı.','Son düzlüktesiniz.'];mikiMessage.textContent=messages[stage]}
function completeSession(){const completedMode=state.mode;stopTimer();if(completedMode==='focus'){ensureCurrentDay();state.stats.minutes+=Number(state.settings.focus);state.stats.pomodoros+=1;updateStreak();saveStats();renderStats();mikiScene.className='miki-scene stage-3 celebrate';mikiMessage.textContent='Miki seninle gurur duyuyor!';showToast('Bir Pomodoro daha tamamlandı ✦')}if('vibrate'in navigator)navigator.vibrate([180,90,180]);playTone();window.setTimeout(()=>setMode(completedMode==='focus'?'short':'focus'),2200)}
function updateStreak(){const today=todayKey();if(state.stats.lastStudyDate===today)return;state.stats.streak=state.stats.lastStudyDate===previousDayKey()?state.stats.streak+1:1;state.stats.lastStudyDate=today}
function resetTimer(){stopTimer();state.remaining=durationFor(state.mode);renderTimer();renderMiki()}
function saveStats(){localStorage.setItem('bernaStats',JSON.stringify(state.stats))}
function saveSettings(){state.settings={focus:clampInput('#focusDuration',1,90),short:clampInput('#shortDuration',1,30),long:clampInput('#longDuration',1,60),dailyGoal:clampInput('#dailyGoal',10,600),darkness:Number($('#backgroundDarkness').value),blur:Number($('#backgroundBlur').value)};localStorage.setItem('bernaSettings',JSON.stringify(state.settings));applyBackgroundControls();resetTimer();renderStats();showToast('Ayarlar kaydedildi')}
function clampInput(selector,min,max){return Math.min(max,Math.max(min,Number($(selector).value)||min))}
function renderStats(){ensureCurrentDay();todayMinutes.textContent=state.stats.minutes>=60?`${Math.floor(state.stats.minutes/60)} sa ${state.stats.minutes%60} dk`:`${state.stats.minutes} dk`;pomodoroCount.textContent=state.stats.pomodoros;streakCount.textContent=`${state.stats.streak} gün`;streakMessage.textContent=state.stats.streak>0?'Ritmi bozma. Bugünkü hedefini tamamla.':'İlk çalışma gününü başlat.';const percent=Math.min(100,Math.round(state.stats.minutes/state.settings.dailyGoal*100));goalLabel.textContent=`${state.stats.minutes} / ${state.settings.dailyGoal} dk`;goalPercent.textContent=`${percent}%`;progressBar.style.width=`${percent}%`}
function playTone(){try{const audio=new(window.AudioContext||window.webkitAudioContext)(),osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.value=880;gain.gain.setValueAtTime(.0001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.16,audio.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.5);osc.start();osc.stop(audio.currentTime+.52)}catch{}}
function openSettings(){['focus','short','long'].forEach(k=>$(`#${k}Duration`).value=state.settings[k]);$('#dailyGoal').value=state.settings.dailyGoal;$('#backgroundDarkness').value=state.settings.darkness;$('#backgroundBlur').value=state.settings.blur;updateRangeLabels();settingsDialog.showModal()}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.id);showToast.id=setTimeout(()=>toast.classList.remove('show'),1900)}
function applyBackgroundControls(){document.documentElement.style.setProperty('--overlay',String(state.settings.darkness/100));document.documentElement.style.setProperty('--blur',`${state.settings.blur}px`)}
function updateRangeLabels(){$('#darknessValue').textContent=`${$('#backgroundDarkness').value}%`;$('#blurValue').textContent=`${$('#backgroundBlur').value} px`;document.documentElement.style.setProperty('--overlay',String(Number($('#backgroundDarkness').value)/100));document.documentElement.style.setProperty('--blur',`${$('#backgroundBlur').value}px`)}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('bernaDB',1);req.onupgradeneeded=()=>req.result.createObjectStore('assets');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function saveBackground(file){if(!file||!file.type.startsWith('image/'))return;const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction('assets','readwrite');tx.objectStore('assets').put(file,'background');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();await loadBackground();showToast('Arka plan kaydedildi')}
async function loadBackground(){try{const db=await openDB();const file=await new Promise((resolve,reject)=>{const req=db.transaction('assets').objectStore('assets').get('background');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();if(file){if(photoBackground.dataset.url)URL.revokeObjectURL(photoBackground.dataset.url);const url=URL.createObjectURL(file);photoBackground.dataset.url=url;photoBackground.style.backgroundImage=`url("${url}")`;photoBackground.classList.add('active')}else{photoBackground.style.backgroundImage='';photoBackground.classList.remove('active')}}catch{}}
async function removeBackground(){try{const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction('assets','readwrite');tx.objectStore('assets').delete('background');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();await loadBackground();showToast('Arka plan kaldırıldı')}catch{showToast('Fotoğraf kaldırılamadı')}}
document.querySelectorAll('.mode-tab').forEach(tab=>tab.addEventListener('click',()=>setMode(tab.dataset.mode)));startButton.addEventListener('click',toggleTimer);resetButton.addEventListener('click',resetTimer);$('#settingsButton').addEventListener('click',openSettings);$('#saveSettingsButton').addEventListener('click',saveSettings);$('#clearDataButton').addEventListener('click',()=>{if(!confirm('Tüm çalışma istatistikleri silinsin mi?'))return;state.stats={date:todayKey(),minutes:0,pomodoros:0,streak:0,lastStudyDate:null};saveStats();renderStats();showToast('İstatistikler sıfırlandı')});
$('#backgroundInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(file){await saveBackground(file);e.target.value=''}});$('#removeBackgroundButton').addEventListener('click',removeBackground);$('#backgroundDarkness').addEventListener('input',updateRangeLabels);$('#backgroundBlur').addEventListener('input',updateRangeLabels);$('#mikiButton').addEventListener('click',()=>{mikiScene.classList.remove('petted');void mikiScene.offsetWidth;mikiScene.classList.add('petted');mikiMessage.textContent=state.running?'Miki odaklanmana eşlik ediyor.':'Miki sevildi.';showToast('Miki: mırıldan…')});
subjectSelect.value=localStorage.getItem('bernaSubject')||'Psikoloji';subjectSelect.addEventListener('change',()=>localStorage.setItem('bernaSubject',subjectSelect.value));window.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.running)tick()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
applyBackgroundControls();loadBackground();setMode('focus');renderStats();
