const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DEFAULTS={focus:25,short:5,long:15,dailyGoal:120,autoStart:false,ambientVolume:28,theme:'paper',time:'evening',season:'autumn',weather:'clear',cat:'tabby'};
const THEMES=[['midnight','Gece','#151019','#6e5267'],['paper','Kâğıt','#eee8df','#a8927c'],['forest','Orman','#0f1812','#7fa36f'],['ocean','Okyanus','#0c1720','#5aa7c1'],['lavender','Lavanta','#17121e','#ae87c7'],['sunset','Gün batımı','#21120f','#d98862']];
const TIMES=[['morning','Sabah'],['day','Gündüz'],['evening','Akşam'],['night','Gece']];
const SEASONS=[['spring','İlkbahar'],['summer','Yaz'],['autumn','Sonbahar'],['winter','Kış']];
const WEATHERS=[['clear','Açık'],['cloudy','Bulutlu'],['rain','Yağmur'],['snow','Kar']];
const CATS=[['tabby','Tekir'],['black','Siyah'],['ginger','Sarman'],['calico','Calico'],['tuxedo','Smokin'],['van','Van desenli'],['white','Beyaz']];
const ITEMS={
 woven_rug:{name:'Dokuma halı',price:60,category:'floor',desc:'Okuma köşesine sıcaklık katar.',pos:[33,66,30],starter:true},
 cat_bed:{name:'Kedi yatağı',price:120,category:'floor',desc:'Miki’nin kendi küçük yatağı.',pos:[67,70,16],starter:true},
 desk:{name:'Çalışma masası',price:220,category:'furniture',desc:'Odak notları için geniş masa.',pos:[12,44,31]},
 bookshelf:{name:'Kitaplık',price:180,category:'furniture',desc:'Duvarı kitaplarla doldurur.',pos:[4,26,17]},
 plant:{name:'Sarmaşık bitki',price:90,category:'decor',desc:'Çatı katına biraz yaşam.',pos:[83,51,11]},
 desk_lamp:{name:'Masa lambası',price:140,category:'decor',desc:'Akşam çalışmalarında sıcak ışık.',pos:[37,46,8]},
 aquarium:{name:'Mini akvaryum',price:350,category:'special',desc:'Sessiz, mavi bir köşe.',pos:[17,58,15]},
 curtains:{name:'Keten perdeler',price:150,category:'wall',desc:'Büyük gözlem penceresini çerçeveler.',pos:[57,11,23]},
 wall_shelf:{name:'Duvar rafı',price:100,category:'wall',desc:'Küçük kitaplar ve bitkiler.',pos:[28,29,18]},
 poster:{name:'Botanik poster',price:80,category:'wall',desc:'Miki’nin sevdiği yeşil poster.',pos:[48,24,11]},
 fairy_lights:{name:'Işık zinciri',price:110,category:'wall',desc:'Çatı boyunca minik ışıklar.',pos:[24,12,31]},
 record_player:{name:'Pikap',price:500,category:'special',desc:'Odaya yumuşak bir melodi hissi.',pos:[79,48,14]},
 yarn_basket:{name:'Yün sepeti',price:95,category:'decor',desc:'Miki’nin oyun köşesi.',pos:[70,75,11]},
 moon_lamp:{name:'Ay lambası',price:260,category:'special',desc:'Gece odasında ay gibi parlar.',pos:[72,31,9]},
 star_projector:{name:'Yıldız projektörü',price:420,category:'hidden',desc:'20 Pomodoro sonrası bulunan gizli eşya.',pos:[56,61,9],unlock:'pomodoro'},
 memory_box:{name:'Anı kutusu',price:0,category:'hidden',desc:'7 günlük seriyle açılan sürpriz.',pos:[42,72,10],unlock:'streak'}
};
const FOODS={basic:{name:'Günlük mama',icon:'🥣',cost:8,hunger:25,xp:0},premium:{name:'Premium mama',icon:'🍗',cost:18,hunger:45,xp:1},fish:{name:'Balık ziyafeti',icon:'🐟',cost:30,hunger:70,xp:2}};
const STAGES=[{id:'baby',name:'Yavru Miki',min:0,next:8},{id:'young',name:'Genç Miki',min:8,next:25},{id:'teen',name:'Büyüyen Miki',min:25,next:60},{id:'adult',name:'Yetişkin Miki',min:60,next:120}];
const INITIAL_SUBJECTS=['Psikoloji','İngilizce','Python','Genel tekrar'];
function loadObj(k,f){try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return {...f}}}function loadArr(k,f=[]){try{const x=JSON.parse(localStorage.getItem(k));return Array.isArray(x)?x:f.slice()}catch{return f.slice()}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function key(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function yesterday(){const d=new Date();d.setDate(d.getDate()-1);return key(d)}function uid(){return `${Date.now()}-${Math.random().toString(16).slice(2)}`}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function formatMin(n){return n>=60?`${Math.floor(n/60)} sa ${n%60} dk`:`${n} dk`}function clamp(v,a,b){return Math.min(b,Math.max(a,+v||a))}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
const state={mode:'focus',running:false,remaining:1500,endAt:null,interval:null,settings:loadObj('bernaSettings',DEFAULTS),stats:loadObj('bernaStats',{date:key(),minutes:0,pomodoros:0,streak:0,lastStudyDate:null,totalPomodoros:0}),history:loadObj('bernaHistory',{}),subjectTotals:loadObj('bernaSubjectTotals',{}),tasks:loadArr('bernaTasks'),subjects:loadArr('bernaSubjects',INITIAL_SUBJECTS),sessions:loadArr('bernaSessions'),exam:loadObj('bernaExam',{name:'',date:''}),agenda:loadArr('bernaAgenda'),pet:loadObj('bernaPet',{coins:0,hunger:70,xp:0,inventory:{basic:0,premium:0,fish:0},ownedItems:['woven_rug','cat_bed'],equippedItems:['woven_rug','cat_bed'],migratedV5:false}),friends:loadArr('bernaFriends'),daily:loadObj('bernaDaily',{loginDate:'',loginStreak:0,questDate:'',focusUnits:0,agendaAdds:0,feeds:0,claimed:[],bonusClaimed:false}),friendCode:localStorage.getItem('bernaFriendCode')||`BERN-${Math.random().toString(36).slice(2,6).toUpperCase()}`};
state.pet.inventory={basic:0,premium:0,fish:0,...(state.pet.inventory||{})};state.pet.ownedItems=Array.isArray(state.pet.ownedItems)?state.pet.ownedItems:['woven_rug','cat_bed'];state.pet.equippedItems=Array.isArray(state.pet.equippedItems)?state.pet.equippedItems:['woven_rug','cat_bed'];localStorage.setItem('bernaFriendCode',state.friendCode);
let selectedDate=key(),calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),shopFilter='all',agendaFilter='all',ambient={ctx:null,nodes:[],playing:false};
function migrate(){if(!state.pet.migratedV5){state.pet.xp=Math.max(state.pet.xp||0,state.stats.totalPomodoros||0);state.pet.ownedItems=[...new Set(['woven_rug','cat_bed',...state.pet.ownedItems])];state.pet.equippedItems=[...new Set(['woven_rug','cat_bed',...state.pet.equippedItems])];state.pet.migratedV5=true;save('bernaPet',state.pet)}save('bernaSettings',state.settings)}
function ensureDay(){if(state.stats.date!==key()){state.stats.date=key();state.stats.minutes=0;state.stats.pomodoros=0;save('bernaStats',state.stats)}if(state.daily.questDate!==key()){state.daily.questDate=key();state.daily.focusUnits=0;state.daily.agendaAdds=0;state.daily.feeds=0;state.daily.claimed=[];state.daily.bonusClaimed=false;save('bernaDaily',state.daily)}}
function stage(){return [...STAGES].reverse().find(s=>(state.pet.xp||0)>=s.min)||STAGES[0]}function growth(){const s=stage(),p=s.id==='adult'?100:Math.round(((state.pet.xp-s.min)/(s.next-s.min))*100);return{s,p:Math.max(0,Math.min(100,p))}}
function duration(m){return Math.max(1,+state.settings[m]||DEFAULTS[m])*60}function focusUnits(min){return Math.floor(min/25)}
function setPage(id){$$('.main-tab').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));if(id==='agendaPage')renderAgenda();if(id==='roomPage')renderRoomAll();if(id==='tasksPage'){renderTasks();renderQuests()}if(id==='profilePage')renderProfile();window.scrollTo({top:0,behavior:'smooth'})}
function setMode(m){stopTimer();state.mode=m;state.remaining=duration(m);$$('.mode-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));const c={focus:['ODAK ZAMANI','Her tam 25 dakikalık odak 10 coin kazandırır.'],short:['KISA MOLA','Miki de biraz dinleniyor.'],long:['UZUN MOLA','Zihnini dinlendirecek kadar uzaklaş.']}[m];$('#modeLabel').textContent=c[0];$('#sessionHint').textContent=c[1];renderTimer();renderFocusCat()}
function renderTimer(){const m=Math.floor(state.remaining/60),s=state.remaining%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;document.title=`${$('#timer').textContent} · Berna`}
function startTimer(){if(state.running)return;state.running=true;state.endAt=Date.now()+state.remaining*1000;$('#startButton').textContent='Duraklat';state.interval=setInterval(tick,250);renderFocusCat()}function stopTimer(){state.running=false;state.endAt=null;clearInterval(state.interval);state.interval=null;$('#startButton').textContent='Başlat';renderFocusCat()}function tick(){const r=Math.max(0,Math.ceil((state.endAt-Date.now())/1000));if(r!==state.remaining){state.remaining=r;renderTimer()}if(r===0)completeSession()}function resetTimer(){stopTimer();state.remaining=duration(state.mode);renderTimer();renderFocusCat()}
function renderFocusCat(){const cat=$('#focusCat');cat.src=`assets/cats/${state.settings.cat}.png`;cat.className='pixel-cat focus-cat';const s=stage();$('#focusStageBadge').textContent=s.name;if(state.mode!=='focus'||(!state.running&&state.remaining===duration('focus'))){cat.classList.add('sleeping');$('#mikiMessage').textContent=`${s.name} seninle çalışmaya hazır.`}else{cat.classList.add('running');$('#mikiMessage').textContent='Miki sessizce yanında odaklanıyor.'}}
function completeSession(){const completed=state.mode;stopTimer();if(completed==='focus'){ensureDay();const mins=+state.settings.focus,units=focusUnits(mins);state.stats.minutes+=mins;state.stats.pomodoros++;state.stats.totalPomodoros=(state.stats.totalPomodoros||0)+1;if(state.stats.lastStudyDate!==key()){state.stats.streak=state.stats.lastStudyDate===yesterday()?state.stats.streak+1:1;state.stats.lastStudyDate=key()}state.history[key()]=(state.history[key()]||0)+mins;const sub=$('#subjectSelect').value;state.subjectTotals[sub]=(state.subjectTotals[sub]||0)+mins;state.sessions.unshift({date:new Date().toISOString(),subject:sub,minutes:mins,note:$('#focusNote').value.trim()});state.sessions=state.sessions.slice(0,40);if(units){state.pet.coins+=units*10;state.pet.xp+=units;state.pet.hunger=Math.max(0,state.pet.hunger-units*6);state.daily.focusUnits+=units}save('bernaStats',state.stats);save('bernaHistory',state.history);save('bernaSubjectTotals',state.subjectTotals);save('bernaSessions',state.sessions);save('bernaPet',state.pet);save('bernaDaily',state.daily);renderStats();renderQuests();const cat=$('#focusCat');cat.className='pixel-cat focus-cat celebrate';$('#mikiMessage').textContent=units?`Harika! +${units*10} coin ve +${units} büyüme.`:'Oturum tamamlandı.';toast(units?`+${units*10} coin`:'Pomodoro tamamlandı')}playTone();if(navigator.vibrate)navigator.vibrate([130,70,130]);const next=completed==='focus'?(state.stats.pomodoros%4===0?'long':'short'):'focus';setTimeout(()=>{setMode(next);if(state.settings.autoStart)startTimer()},1500)}
function playTone(){try{const A=window.AudioContext||window.webkitAudioContext,c=new A(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=850;g.gain.setValueAtTime(.001,c.currentTime);g.gain.exponentialRampToValueAtTime(.14,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.4);o.start();o.stop(c.currentTime+.42)}catch{}}
function renderStats(){ensureDay();$('#todayMinutes').textContent=formatMin(state.stats.minutes);$('#focusCoins').textContent=state.pet.coins;$('#headerCoins').textContent=state.pet.coins;$('#streakCount').textContent=`${state.stats.streak} gün`;$('#streakMessage').textContent=state.stats.streak?'Ritmi bozma. Miki seni bekliyor.':'İlk çalışma gününü başlat.';const p=Math.min(100,Math.round(state.stats.minutes/state.settings.dailyGoal*100));$('#goalLabel').textContent=`${state.stats.minutes} / ${state.settings.dailyGoal} dk`;$('#goalPercent').textContent=`${p}%`;$('#progressBar').style.width=`${p}%`;renderFocusCat()}
function renderSubjects(){const html=state.subjects.map(s=>`<option>${esc(s)}</option>`).join('');$('#subjectSelect').innerHTML=html;$('#agendaSubject').innerHTML=html;const old=localStorage.getItem('bernaSubject');if(state.subjects.includes(old))$('#subjectSelect').value=old;$('#subjectList').innerHTML=state.subjects.map((s,i)=>`<span class="chip">${esc(s)}${state.subjects.length>1?`<button data-del-subject="${i}" type="button">×</button>`:''}</span>`).join('')}
function addSubject(){const v=$('#subjectInput').value.trim();if(!v||state.subjects.includes(v))return;state.subjects.push(v);save('bernaSubjects',state.subjects);$('#subjectInput').value='';renderSubjects()}function renderTasks(){const done=state.tasks.filter(t=>t.done).length;$('#taskSummary').textContent=`${done} / ${state.tasks.length}`;$('#taskList').innerHTML=state.tasks.length?state.tasks.map((t,i)=>`<div class="task-item ${t.done?'done':''}"><input class="task-check" type="checkbox" data-toggle-task="${i}" ${t.done?'checked':''}><span class="task-text">${esc(t.text)}</span><button class="delete-button" data-del-task="${i}" type="button">×</button></div>`).join(''):'<div class="empty-state">Bugün için görev yok.</div>'}function addTask(){const v=$('#taskInput').value.trim();if(!v)return;state.tasks.push({text:v,done:false});save('bernaTasks',state.tasks);$('#taskInput').value='';renderTasks()}
function renderCalendar(){const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=new Date(y,m,1),off=(first.getDay()+6)%7;$('#calendarTitle').textContent=calendarMonth.toLocaleDateString('tr-TR',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());const cells=[];for(let i=0;i<42;i++){const d=new Date(y,m,1-off+i),k=key(d),has=state.agenda.some(a=>a.date===k);cells.push(`<button class="calendar-day ${d.getMonth()===m?'':'other'} ${k===key()?'today':''} ${k===selectedDate?'selected':''} ${has?'has-plan':''}" data-date="${k}" type="button">${d.getDate()}</button>`)}$('#calendarGrid').innerHTML=cells.join('')}
function agendaItemsForSelectedDate(){
 const items=state.agenda.filter(a=>a.date===selectedDate).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));
 if(agendaFilter==='pending')return items.filter(a=>!a.done);
 if(agendaFilter==='done')return items.filter(a=>a.done);
 return items
}
function renderAgendaList(){
 const d=new Date(`${selectedDate}T12:00:00`);
 $('#selectedDateTitle').textContent=selectedDate===key()?'Bugün':d.toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long'}).replace(/^./,c=>c.toUpperCase());
 const all=state.agenda.filter(a=>a.date===selectedDate).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));
 const done=all.filter(a=>a.done).length;
 const percent=all.length?Math.round(done/all.length*100):0;
 $('#agendaSummary').textContent=`${done} / ${all.length} tamamlandı`;
 $('#agendaProgressBar').style.width=`${percent}%`;
 $('#agendaProgressText').textContent=`${percent}%`;
 $('#clearCompletedAgenda').disabled=done===0;
 const arr=agendaItemsForSelectedDate();
 $('#agendaList').innerHTML=arr.length?arr.map(a=>`<div class="agenda-item ${a.done?'done':''}">
  <label class="agenda-check-wrap" title="${a.done?'Tamamlandı':'Tamamlandı olarak işaretle'}">
    <input class="task-check" type="checkbox" data-toggle-agenda="${a.id}" ${a.done?'checked':''}>
    <span class="custom-check" aria-hidden="true">✓</span>
  </label>
  <div class="agenda-copy">
    <strong>${esc(a.title)}</strong>
    <small>${a.time?`<span class="agenda-time">${a.time}</span> · `:''}${esc(a.subject)}</small>
  </div>
  <button class="delete-button" data-del-agenda="${a.id}" type="button" aria-label="Maddeden sil">×</button>
 </div>`).join(''):`<div class="empty-state">${agendaFilter==='pending'?'Yapılacak madde kalmadı. Harika!':agendaFilter==='done'?'Henüz tamamlanan madde yok.':'Bu güne henüz bir yapılacak eklenmedi.'}</div>`
}
function renderAgenda(){renderCalendar();renderAgendaList()}
function addAgenda(){
 const title=$('#agendaTitle').value.trim();if(!title)return;
 state.agenda.push({id:uid(),title,date:selectedDate,time:$('#agendaTime').value,subject:$('#agendaSubject').value,done:false});
 state.daily.agendaAdds++;save('bernaAgenda',state.agenda);save('bernaDaily',state.daily);
 $('#agendaTitle').value='';$('#agendaTime').value='';agendaFilter='all';
 $$('[data-agenda-filter]').forEach(x=>x.classList.toggle('active',x.dataset.agendaFilter==='all'));
 renderAgenda();renderQuests();toast('Yapılacaklara eklendi')
}
function itemUnlocked(id){const it=ITEMS[id];if(!it.unlock)return true;if(it.unlock==='pomodoro')return (state.stats.totalPomodoros||0)>=20;if(it.unlock==='streak')return (state.stats.streak||0)>=7;return false}function itemOwned(id){return state.pet.ownedItems.includes(id)}function itemEquipped(id){return state.pet.equippedItems.includes(id)}
function renderRoom(){const room=$('#pixelRoom');room.dataset.time=state.settings.time;room.dataset.season=state.settings.season;room.dataset.weather=state.settings.weather;$('#seasonOverlay').src=`assets/room/season_${state.settings.season}.png`;$('#roomCat').src=`assets/cats/${state.settings.cat}.png`;const g=growth();$('#roomStageTitle').textContent=`${g.s.name}’nin çatı katı`;$('#roomCoins').textContent=state.pet.coins;$('#petGrowthText').textContent=g.s.id==='adult'?`${state.pet.xp} büyüme`:`${state.pet.xp} / ${g.s.next}`;$('#petGrowthBar').style.width=`${g.p}%`;$('#petHungerText').textContent=`${state.pet.hunger}%`;$('#petHungerBar').style.width=`${state.pet.hunger}%`;$('#petMessage').textContent=state.pet.hunger<25?'Miki acıkmış. Mama bölümünden onu besle.':'Miki bu sakin çatı katını seviyor.';$('#roomItems').innerHTML=state.pet.equippedItems.filter(id=>ITEMS[id]&&itemUnlocked(id)).map(id=>{const [l,t,w]=ITEMS[id].pos;return `<img class="room-item" src="assets/items/${id}.png" alt="" style="left:${l}%;top:${t}%;width:${w}%">`}).join('')}
function choiceHTML(list,current,type){return list.map(([id,n])=>`<button class="choice-button ${current===id?'active':''}" data-choice-type="${type}" data-choice="${id}" type="button">${n}</button>`).join('')}
function renderControls(){$('#timeChoices').innerHTML=choiceHTML(TIMES,state.settings.time,'time');$('#seasonChoices').innerHTML=choiceHTML(SEASONS,state.settings.season,'season');$('#weatherChoices').innerHTML=choiceHTML(WEATHERS,state.settings.weather,'weather');$('#catChoices').innerHTML=CATS.map(([id,n])=>`<button class="cat-choice ${state.settings.cat===id?'active':''}" data-cat="${id}" type="button"><img src="assets/cats/${id}.png" alt="${n}"><small>${n}</small></button>`).join('');$('#selectedCatName').textContent=CATS.find(x=>x[0]===state.settings.cat)?.[1]||'Tekir'}
function renderRoomShop(){const ids=Object.keys(ITEMS).filter(id=>itemUnlocked(id)).filter(id=>shopFilter==='all'||itemOwned(id));$('#roomShop').innerHTML=ids.map(id=>{const it=ITEMS[id],owned=itemOwned(id),equipped=itemEquipped(id);return `<article class="shop-item ${it.category==='hidden'?'hidden-item':''}"><img src="assets/items/${id}.png" alt="${it.name}"><div class="shop-copy"><strong>${it.name}</strong><small>${it.desc}</small><div class="shop-price">${owned?'Sahipsin':it.price?`● ${it.price}`:'Özel ödül'}</div><button class="shop-action ${owned?'secondary':''}" data-room-action="${owned?(equipped?'remove':'place'):'buy'}" data-item="${id}" type="button">${owned?(equipped?'Odadan kaldır':'Odaya koy'):'Satın al'}</button></div></article>`}).join('')||'<div class="empty-state">Bu bölümde eşya yok.</div>'}
function buyOrToggle(id,action){const it=ITEMS[id];if(!it||!itemUnlocked(id))return;if(action==='buy'){if(state.pet.coins<it.price){toast('Yeterli coin yok');return}state.pet.coins-=it.price;state.pet.ownedItems.push(id);state.pet.equippedItems.push(id);toast(`${it.name} alındı`)}else if(action==='place'){state.pet.equippedItems.push(id);toast('Odaya yerleştirildi')}else{state.pet.equippedItems=state.pet.equippedItems.filter(x=>x!==id);toast('Odadan kaldırıldı')}state.pet.ownedItems=[...new Set(state.pet.ownedItems)];state.pet.equippedItems=[...new Set(state.pet.equippedItems)];save('bernaPet',state.pet);renderRoomAll();renderStats()}
function renderFood(){const total=Object.values(state.pet.inventory).reduce((a,b)=>a+b,0);$('#foodInventoryCount').textContent=`${total} mama`;$('#foodShop').innerHTML=Object.entries(FOODS).map(([id,f])=>`<article class="food-item"><span class="food-icon">${f.icon}</span><div><strong>${f.name}</strong><small>Tokluk +${f.hunger}${f.xp?` · büyüme +${f.xp}`:''}</small><span class="shop-price">● ${f.cost} · Çantada ${state.pet.inventory[id]||0}</span></div><div class="food-buttons"><button class="secondary-button" data-buy-food="${id}" type="button">Al</button><button class="primary-button" data-feed-food="${id}" type="button" ${state.pet.inventory[id]?'':'disabled'}>Yedir</button></div></article>`).join('')}
function buyFood(id){const f=FOODS[id];if(state.pet.coins<f.cost){toast('Yeterli coin yok');return}state.pet.coins-=f.cost;state.pet.inventory[id]=(state.pet.inventory[id]||0)+1;save('bernaPet',state.pet);renderRoomAll();renderStats();toast(`${f.name} alındı`)}function feedFood(id){const f=FOODS[id];if(!state.pet.inventory[id])return;state.pet.inventory[id]--;state.pet.hunger=Math.min(100,state.pet.hunger+f.hunger);state.pet.xp+=f.xp;state.pet.lastFedAt=new Date().toISOString();state.daily.feeds++;save('bernaPet',state.pet);save('bernaDaily',state.daily);renderRoomAll();renderStats();renderQuests();toast('Miki mutlu ve tok')}
function renderRoomAll(){renderRoom();renderControls();renderRoomShop();renderFood()}
function quests(){return[{id:'focus',title:'2 odak birimi tamamla',value:state.daily.focusUnits,target:2,reward:15},{id:'agenda',title:'Ajandaya 1 plan ekle',value:state.daily.agendaAdds,target:1,reward:10},{id:'feed',title:'Miki’yi 1 kez besle',value:state.daily.feeds,target:1,reward:10}]}function renderQuests(){ensureDay();const qs=quests();$('#dailyQuests').innerHTML=qs.map(q=>{const done=q.value>=q.target,claimed=state.daily.claimed.includes(q.id);return `<div class="quest-item ${claimed?'claimed':''}"><div class="quest-copy"><strong>${q.title}</strong><small>${Math.min(q.value,q.target)} / ${q.target}</small></div><button class="${done&&!claimed?'primary-button':'secondary-button'} compact" data-claim-quest="${q.id}" type="button" ${!done||claimed?'disabled':''}>${claimed?'Alındı':`+${q.reward}`}</button></div>`}).join('');const all=qs.every(q=>state.daily.claimed.includes(q.id));$('#dailyQuestBonus').textContent=state.daily.bonusClaimed?'Bonus alındı':all?'+20 hazır':'+20 bonus'}function claimQuest(id){const q=quests().find(x=>x.id===id);if(!q||q.value<q.target||state.daily.claimed.includes(id))return;state.daily.claimed.push(id);state.pet.coins+=q.reward;const all=quests().every(x=>state.daily.claimed.includes(x.id));if(all&&!state.daily.bonusClaimed){state.daily.bonusClaimed=true;state.pet.coins+=20;toast(`Görev + bonus: +${q.reward+20} coin`)}else toast(`+${q.reward} coin`);save('bernaDaily',state.daily);save('bernaPet',state.pet);renderQuests();renderStats()}
function claimDaily(){if(state.daily.loginDate===key())return;state.daily.loginStreak=state.daily.loginDate===yesterday()?Math.min(7,state.daily.loginStreak+1):1;state.daily.loginDate=key();const reward=[0,10,15,20,25,30,40,60][state.daily.loginStreak];state.pet.coins+=reward;save('bernaDaily',state.daily);save('bernaPet',state.pet);renderDailyLogin();renderStats();toast(`Günlük hediye: +${reward} coin`)}function renderDailyLogin(){const claimed=state.daily.loginDate===key(),next=claimed?'Bugünün hediyesi alındı':`${Math.min(7,state.daily.loginStreak+1)}. gün hediyesi`;$('#dailyLoginTitle').textContent=next;$('#dailyLoginText').textContent=claimed?'Yarın yeniden gel.':`Seri: ${state.daily.loginStreak} gün`;$('#claimDailyButton').disabled=claimed;$('#claimDailyButton').textContent=claimed?'Alındı':'Hediyeyi al'}
function renderFriends(){$('#myFriendCode').textContent=state.friendCode;$('#friendCount').textContent=`${state.friends.length} arkadaş`;$('#friendList').innerHTML=state.friends.length?state.friends.map(f=>`<div class="friend-item"><div><strong>${esc(f.name)}</strong><small>${esc(f.code)} · Eklendi</small></div><button class="delete-button" data-del-friend="${f.id}" type="button">×</button></div>`).join(''):'<div class="empty-state">Henüz arkadaş eklenmedi.</div>'}function addFriend(){const name=$('#friendName').value.trim(),code=$('#friendCode').value.trim().toUpperCase();if(!name||!/^BERN-[A-Z0-9]{4}$/.test(code)){toast('Ad ve BERN-XXXX kodu gerekli');return}if(state.friends.some(f=>f.code===code)){toast('Bu arkadaş zaten ekli');return}state.friends.push({id:uid(),name,code});save('bernaFriends',state.friends);$('#friendName').value='';$('#friendCode').value='';renderFriends();toast('Arkadaş eklendi')}
function last7(){const a=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);a.push({k:key(d),label:['Paz','Pzt','Sal','Çar','Per','Cum','Cmt'][d.getDay()]})}return a}function renderChart(){const ds=last7(),vals=ds.map(d=>state.history[d.k]||0),max=Math.max(30,...vals);$('#weekTotal').textContent=formatMin(vals.reduce((a,b)=>a+b,0));$('#weekChart').innerHTML=ds.map((d,i)=>`<div class="bar-wrap"><b>${vals[i]}</b><div class="bar" style="height:${Math.max(3,vals[i]/max*120)}px"></div><small>${d.label}</small></div>`).join('')}
function renderBadges(){const p=state.stats.totalPomodoros||0,xp=state.pet.xp||0,b=[['✦','İlk adım',p>=1],['●','İlk coin',xp>=1],['🐾','Genç Miki',xp>=8],['📚','50 Pomodoro',p>=50],['🔥','7 günlük seri',state.stats.streak>=7],['🥣','Bakım veren',!!state.pet.lastFedAt],['🏠','İlk eşya',state.pet.ownedItems.length>=3],['✨','Gizli eşya',itemOwned('star_projector')||itemOwned('memory_box')],['👥','İlk arkadaş',state.friends.length>=1],['🏛','Yetişkin Miki',xp>=60]];$('#badgeCount').textContent=`${b.filter(x=>x[2]).length} / ${b.length}`;$('#badgeGrid').innerHTML=b.map(x=>`<article class="achievement ${x[2]?'unlocked':''}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]?'Kazanıldı':'Henüz kilitli'}</small></article>`).join('')}
function renderExam(){$('#examName').value=state.exam.name||'';$('#examDate').value=state.exam.date||'';if(!state.exam.date){$('#examCountdown').innerHTML='<strong>Henüz sınav yok</strong><small>Bir tarih eklediğinde geri sayım başlar.</small>';return}const diff=new Date(`${state.exam.date}T23:59:59`)-Date.now(),days=Math.max(0,Math.ceil(diff/86400000));$('#examCountdown').innerHTML=diff<0?`<strong>Tarih geçti</strong><small>${esc(state.exam.name||'Sınav')}</small>`:`<strong>${days} gün kaldı</strong><small>${esc(state.exam.name||'Sınav')}</small>`}function saveExam(){state.exam={name:$('#examName').value.trim(),date:$('#examDate').value};save('bernaExam',state.exam);renderExam();toast('Sınav kaydedildi')}
function renderSessions(){$('#sessionLog').innerHTML=state.sessions.length?state.sessions.slice(0,10).map(s=>{const d=new Date(s.date);return `<div class="session-entry"><strong>${esc(s.subject)}</strong><span>${d.toLocaleDateString('tr-TR',{day:'numeric',month:'short'})} · ${s.minutes} dk</span><small>${s.note?esc(s.note):'Not eklenmedi'}</small></div>`}).join(''):'<div class="empty-state">Tamamlanan oturumlar burada görünür.</div>'}
function renderProfile(){renderDailyLogin();renderFriends();renderChart();renderBadges();renderExam();renderSessions()}
function applyTheme(){document.body.dataset.theme=state.settings.theme;const t=THEMES.find(x=>x[0]===state.settings.theme)||THEMES[0];document.querySelector('meta[name="theme-color"]').content=t[2]}function renderThemes(){$('#themeGrid').innerHTML=THEMES.map(([id,n,a,b])=>`<button class="theme-option ${state.settings.theme===id?'active':''}" data-theme="${id}" type="button"><span class="theme-preview" style="--a:${a};--b:${b}"></span><small>${n}</small></button>`).join('')}
function openSettings(){['focus','short','long'].forEach(k=>$(`#${k}Duration`).value=state.settings[k]);$('#dailyGoal').value=state.settings.dailyGoal;$('#autoStart').checked=!!state.settings.autoStart;$('#ambientVolume').value=state.settings.ambientVolume;$('#ambientVolumeValue').textContent=`${state.settings.ambientVolume}%`;renderThemes();$('#settingsDialog').showModal()}function saveSettings(){state.settings={...state.settings,focus:clamp($('#focusDuration').value,1,120),short:clamp($('#shortDuration').value,1,30),long:clamp($('#longDuration').value,1,60),dailyGoal:clamp($('#dailyGoal').value,10,600),autoStart:$('#autoStart').checked,ambientVolume:+$('#ambientVolume').value};save('bernaSettings',state.settings);applyTheme();resetTimer();renderStats();$('#settingsDialog').close();toast('Ayarlar kaydedildi')}
function stopAmbient(){ambient.nodes.forEach(n=>{try{n.stop?.();n.disconnect?.()}catch{}});ambient.nodes=[];ambient.playing=false;$('#ambientToggle').textContent='Çal'}function startAmbient(type){stopAmbient();if(type==='off')return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=ambient.ctx||(ambient.ctx=new A());c.resume();const master=c.createGain();master.gain.value=state.settings.ambientVolume/100*.32;master.connect(c.destination);ambient.nodes.push(master);const noise=(ft,f,v)=>{const size=c.sampleRate*2,b=c.createBuffer(1,size,c.sampleRate),data=b.getChannelData(0);let last=0;for(let i=0;i<size;i++){const w=Math.random()*2-1;last=(last+.02*w)/1.02;data[i]=type==='brown'?last*3.5:w}const s=c.createBufferSource(),fl=c.createBiquadFilter(),g=c.createGain();s.buffer=b;s.loop=true;fl.type=ft;fl.frequency.value=f;g.gain.value=v;s.connect(fl).connect(g).connect(master);s.start();ambient.nodes.push(s,fl,g)};if(type==='rain'){noise('lowpass',4200,.45);noise('highpass',1800,.18)}if(type==='brown')noise('lowpass',700,.75);if(type==='cafe')noise('bandpass',900,.28);ambient.playing=true;$('#ambientToggle').textContent='Durdur'}
function exportData(){const keys=['bernaSettings','bernaStats','bernaHistory','bernaSubjectTotals','bernaTasks','bernaSubjects','bernaSessions','bernaExam','bernaAgenda','bernaPet','bernaFriends','bernaDaily','bernaFriendCode'];const data={version:'5.1',exportedAt:new Date().toISOString()};keys.forEach(k=>data[k]=localStorage.getItem(k));const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`berna-v5.1-yedek-${key()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Yedek indirildi')}async function importData(file){try{const d=JSON.parse(await file.text());if(!d.version)throw Error();Object.entries(d).forEach(([k,v])=>{if(k.startsWith('berna')&&v!==null)localStorage.setItem(k,v)});toast('Yedek yüklendi');setTimeout(()=>location.reload(),700)}catch{toast('Geçersiz yedek')}}
$$('.main-tab').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));$$('.mode-tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('#startButton').addEventListener('click',()=>state.running?stopTimer():startTimer);$('#resetButton').addEventListener('click',resetTimer);$('#quickAgendaButton').addEventListener('click',()=>setPage('agendaPage'));$('#coinPill').addEventListener('click',()=>setPage('roomPage'));$('#settingsButton').addEventListener('click',openSettings);$('#closeSettingsButton').addEventListener('click',()=>$('#settingsDialog').close());$('#saveSettingsButton').addEventListener('click',saveSettings);$('#ambientVolume').addEventListener('input',e=>$('#ambientVolumeValue').textContent=`${e.target.value}%`);$('#ambientToggle').addEventListener('click',()=>ambient.playing?stopAmbient():startAmbient($('#ambientSelect').value));$('#ambientSelect').addEventListener('change',()=>{if(ambient.playing)startAmbient($('#ambientSelect').value)});$('#subjectSelect').addEventListener('change',e=>localStorage.setItem('bernaSubject',e.target.value));
$('#addTaskButton').addEventListener('click',addTask);$('#taskInput').addEventListener('keydown',e=>{if(e.key==='Enter')addTask()});$('#taskList').addEventListener('click',e=>{if(e.target.dataset.delTask!==undefined)state.tasks.splice(+e.target.dataset.delTask,1);if(e.target.dataset.toggleTask!==undefined)state.tasks[+e.target.dataset.toggleTask].done=e.target.checked;save('bernaTasks',state.tasks);renderTasks()});$('#addSubjectButton').addEventListener('click',addSubject);$('#subjectList').addEventListener('click',e=>{if(e.target.dataset.delSubject!==undefined){state.subjects.splice(+e.target.dataset.delSubject,1);save('bernaSubjects',state.subjects);renderSubjects()}});
$('#prevMonth').addEventListener('click',()=>{calendarMonth.setMonth(calendarMonth.getMonth()-1);renderCalendar()});
$('#nextMonth').addEventListener('click',()=>{calendarMonth.setMonth(calendarMonth.getMonth()+1);renderCalendar()});
$('#calendarGrid').addEventListener('click',e=>{const k=e.target.dataset.date;if(!k)return;selectedDate=k;const d=new Date(`${k}T12:00:00`);calendarMonth=new Date(d.getFullYear(),d.getMonth(),1);agendaFilter='all';$$('[data-agenda-filter]').forEach(x=>x.classList.toggle('active',x.dataset.agendaFilter==='all'));renderAgenda()});
$('#addAgendaButton').addEventListener('click',addAgenda);
$('#agendaTitle').addEventListener('keydown',e=>{if(e.key==='Enter')addAgenda()});
$('#agendaList').addEventListener('click',e=>{const del=e.target.closest('[data-del-agenda]')?.dataset.delAgenda;if(del){state.agenda=state.agenda.filter(a=>a.id!==del);save('bernaAgenda',state.agenda);renderAgenda()}});
$('#agendaList').addEventListener('change',e=>{const tog=e.target.dataset.toggleAgenda;if(!tog)return;const a=state.agenda.find(x=>x.id===tog);if(a)a.done=e.target.checked;save('bernaAgenda',state.agenda);renderAgenda();if(a?.done)toast('Tamamlandı ✓')});
$$('[data-agenda-filter]').forEach(button=>button.addEventListener('click',()=>{agendaFilter=button.dataset.agendaFilter;$$('[data-agenda-filter]').forEach(x=>x.classList.toggle('active',x===button));renderAgendaList()}));
$('#clearCompletedAgenda').addEventListener('click',()=>{const count=state.agenda.filter(a=>a.date===selectedDate&&a.done).length;if(!count)return;state.agenda=state.agenda.filter(a=>a.date!==selectedDate||!a.done);save('bernaAgenda',state.agenda);renderAgenda();toast(`${count} tamamlanan madde temizlendi`)});

document.addEventListener('click',e=>{const c=e.target.closest('[data-choice]');if(c){state.settings[c.dataset.choiceType]=c.dataset.choice;save('bernaSettings',state.settings);renderRoomAll()}const cat=e.target.closest('[data-cat]');if(cat){state.settings.cat=cat.dataset.cat;save('bernaSettings',state.settings);renderRoomAll();renderFocusCat()}const theme=e.target.closest('[data-theme]');if(theme){state.settings.theme=theme.dataset.theme;save('bernaSettings',state.settings);applyTheme();renderThemes()}const filter=e.target.closest('[data-shop-filter]');if(filter){shopFilter=filter.dataset.shopFilter;$$('[data-shop-filter]').forEach(x=>x.classList.toggle('active',x===filter));renderRoomShop()}const action=e.target.closest('[data-room-action]');if(action)buyOrToggle(action.dataset.item,action.dataset.roomAction);const buy=e.target.closest('[data-buy-food]');if(buy)buyFood(buy.dataset.buyFood);const feed=e.target.closest('[data-feed-food]');if(feed)feedFood(feed.dataset.feedFood);const quest=e.target.closest('[data-claim-quest]');if(quest)claimQuest(quest.dataset.claimQuest);const friend=e.target.closest('[data-del-friend]');if(friend){state.friends=state.friends.filter(f=>f.id!==friend.dataset.delFriend);save('bernaFriends',state.friends);renderFriends()}});
$('#claimDailyButton').addEventListener('click',claimDaily);$('#addFriendButton').addEventListener('click',addFriend);$('#copyFriendCode').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(state.friendCode);toast('Kod kopyalandı')}catch{toast(state.friendCode)}});$('#saveExamButton').addEventListener('click',saveExam);$('#exportButton').addEventListener('click',exportData);$('#importInput').addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''});$('#clearDataButton').addEventListener('click',()=>{if(confirm('Tüm Berna verileri silinsin mi?')){Object.keys(localStorage).filter(k=>k.startsWith('berna')).forEach(k=>localStorage.removeItem(k));location.reload()}});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.running)tick()});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
migrate();ensureDay();applyTheme();renderSubjects();renderTasks();renderAgenda();renderRoomAll();renderQuests();renderProfile();setMode('focus');renderStats();